### ISSUE TITLE
Skip particular post to give feedback. 

### ISSUE THREAD

**Issue by sri-shree** [SOBotics/Higgs#63]
Some particular post I am not sure what feedback is appropriate so I want to skip that post. But I can't find any option to skip that post and get new post. So it's useful to allow reviewers to skip that particular post on review queue.  https://higgs.sobotics.org/review

**Comment by rjrudman** [comment]
@sri-shree Currently only heat detector reports are coming through. For these, you should just send the 'sk' feedback

**Comment by sri-shree** [comment]
sk is not a part of feedback ? I miss understood it ??

**Comment by rjrudman** [comment]
Can you show me a screenshot of the review item you're doing? There should be 'sk' 'nc' 'fp' 'fn' 'tp'

**Comment by sri-shree** [comment]
I completely miss under stood about sk.  Now it's clear. No re-pro. Thanks and please closed this issue please.

**Comment by rjrudman** [comment]
@sri-shree 'sk' is actually a feedback type for heat detector, but it's design to skip the review if the person is unsure :)

**Comment by sri-shree** [comment]
Yep that's why I am confuse :) . Thanks.

**Comment by rjrudman** [comment]
@fortune-man technically, yep, it's possible. However, Higgs doesn't really have the concept of reviews (yet). The review page simply displays a report which you haven't supplied feedback to yet. If/when other bots integrate with Higgs, I'll look into it.

Holding off on it now because of 'sk', and to see what other bots might require review-wise before implementing it

**Comment by fortunate-man** [comment]
@rjrudman ok, thanks!

**Comment by rjrudman** [comment]
@fortunate-man I've added an issue here: https://github.com/SOBotics/Higgs/issues/64 so it doesn't get lost/forgotten :)
