### ISSUE TITLE
Show icons, or a count of feedback?

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Higgs#7]

**Comment by Bhargav-Rao** [comment]
My money is on showing icons. 

Both CopyPastor and MetaSmoke do this. Sentinel is the only one which is a bit weird.  Showing count of icons would just involve another layer of complexity. We would need to open another page to see who has actually given feedback.

**Comment by pbdevch** [comment]
I have the same opion as @Bhargav-Rao, especially because we don't have much feedbacks per report (Looking through Sentinel it's just 1 or 2 in most cases, and some bots like Queen/HD are satisfied with one person giving feedback). From that, visibility shouldn't be a concern (Lot's of ✔️ and ❌ next to each other in way that you need to count manually)
